### ISSUE TITLE
discover_cups_printers.pl doesn't work on localized systems

### ISSUE THREAD

**Issue by pavel-shvagirev** [a-schild/zabbix-cups#3]
Just add "LANG=C" at the beginning of the script.

**Comment by pavel-shvagirev** [comment]
Same for /etc/zabbix/zabbix_agentd.d/cups.conf:
add "LANG=C; " before every "lpstat" and restart zabbix_agentd.

**Comment by a-schild** [comment]
Thanks @pavel-shvagirev 
Works now fine
